### ISSUE TITLE
Better coolio emoji needed

### ISSUE THREAD

**Issue by DevinWalker** [mlteal/custom-emoji#2]
## Issue Overview

Coolio is an awesome rapper an his emoji is currently pixelated and his hair needs to have movement to ensure plenty of smiles and laughs.

## Proposed Solution

Use an animated gif like this and downsize properly so it's usable in Slack and the quality is higher:

![coolio](https://cloud.githubusercontent.com/assets/1571635/20868360/c788b814-ba27-11e6-8a42-8bd080079de3.gif)

PR coming soon 😸

**Comment by mlteal** [comment]
Closing, PR #3 merged
